### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by yukichikawada** [yukichikawada/smedium#7]
- [x] Backend: DB, modal, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [ ] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by wongshington** [comment]
Everything is really coming along! As far as user auth:
- [x] renders and clears appropriate errors
- [x] bigger font size on the session forms and for the session buttons
- [x] space out the "write a story" and "log out" buttons once signed in
- [x] the "about membership" and "upgrade" text?
- [x] modal should have a close button as well somewhere in the corner probably

**Comment by wongshington** [comment]
- [x] make the session forms a bit bigger to begin with so they don't resize as much/nothing gets pushed too far to the bottom of the modal
  - right now if you have all the sign up form errors rendering the text at the bottom of the modal is dangerously close to running off the modal

**Comment by yukichikawada** [comment]
Done. Thx.

**Comment by yukichikawada** [comment]
Done. Thx.
