### ISSUE TITLE
PA REVIEW: Stories Full CRUD

### ISSUE THREAD

**Issue by yukichikawada** [yukichikawada/smedium#8]
- [x] Create: Stories - limited to registered Users
- [x] Read: Stories
- [x] Update: Stories - if author is currentUser
- [x] Delete: Stories - if author is currentUser 
- [x] StoryIndex - has IndexItem and StoryDetail components
- [x] StoryForm - containers for Creating and Updating reuse component

**Comment by wongshington** [comment]
- [x] render the photo on the story show page as well
- [x] add "..." after the last bit of the preview that you cut off from the story in the index items

**Comment by yukichikawada** [comment]
Done. Thx.

**Comment by wongshington** [comment]
- [x] can't add a photo to a story
- [x] on story form: "Learn about joining our Partner Program" (what is this for?)
